### ISSUE TITLE
v0.35.0 release plans

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#10662]
Resulting from some IRC discussion, we are currently waiting for the following:

- [x] new wayland vo, removal of vo_vaapi_wayland | #10533 | @Dudemanguy 
- [x] various macOS fixes | ? | @jeeb 
- [x] hw filter and other changes | #10527 | @philipl 
- [x] vo_gpu/hwdec: rename and introduce legacy names for some interops | #10669 | @philipl 
- [x]  hwdec/vaapi: improve probing of supported sw formats | #10655 | @philipl 
- [x]  f_hwtransfer: allow hw uploads to implicitly convert formats | #10698 | @philipl 
- [x] fix heap-buffer-overflow in mark_rect | #9242 | @Dudemanguy 
- [x] x11: fix --on-all-workspaces option | #10729 | @Dudemanguy 
- [x] dmabuf_wayland and (maybe) other wl fixes | #10821 | @sfan5
- [x] two issues noted on IRC | - | @sfan5

<hr>

meson will be supported equally to waf in the next release.

**release target: week 45**

**Comment by Dudemanguy** [comment]
I'm leaning towards just renaming `vo_vaapi_wayland` as a stopgap since these are some big changes that can wait after the release.

**Comment by philipl** [comment]
I want to merge #10527 and then I have a pending changes to rename hwdec-interops (with legacy name compatibility) to clean up  `vaapi-egl` and drmprime-drm` and remove the unnecessary vaapi 'shit list' logic in hwtransfer.

**Comment by christoph-heinrich** [comment]
#10542 is a tiny change, so review should be trivial.
#10596 small change to the documentation to benefit script authors.
#10495 is basically a bug fix for `video-sync=display-*` options, which currently behave suboptimally.
#10315 and #10316 are quite useful when trying out and comparing options in the console.

Not all of them have to land of course, but I think they are the best candidates of my open PRs (otherwise they'll end up years old without any activity :laughing:).

**Comment by Max-Enrik** [comment]
This video player is one of the best. It is very light and uses little resources to play.
Nothing but thanks to the people who made it happen.

**Comment by Dudemanguy** [comment]
Since I just remembered we should probably fix what https://github.com/mpv-player/mpv/pull/9242 fixes this time around (that bug still exists).

**Comment by odnar-dev** [comment]
Please take a look into this [PR](https://github.com/mpv-player/mpv/pull/10636) to fix `--on-all-workspaces` option on xfce

**Comment by VincentVerdynanta** [comment]
Not a critical one, but it would be nice to see PR #10624 getting tested and eventually making its way into the release.

**Comment by laichiaheng** [comment]
Will there be gpu-next in v0.35?

**Comment by Akczht** [comment]
macOS Ventura support , maybe ?

**Comment by Akemi** [comment]
what kind of ventura support? that's quite a vague statement.

the screen selection PR shouldn't be merged in the current state. like i said on there, i believe it would be best practice to move the whole thing into the compatibility file for cleanness and easier removal later.

**Comment by Akczht** [comment]
in waf build tools there are mentions for macOS 10-14 10-12-2 , but not Monterey , I supposed there could've been some compatibility requirements to be made

**Comment by singh-jagjot** [comment]
MacOS fixes will be great, Metal support will be too much to ask but proper playback of HDR files will be great. Thanks for the great effort as always!

**Comment by diederikdehaas** [comment]
It would be great if 0.35 could make it into Debian Bookworm. To achieve that it (normally) needs to be in *Testing* (=Bookworm; till it's released) by 2023-01-12 which means uploaded to *Unstable* ~ a week before that (at the latest).

**Comment by laichiaheng** [comment]
https://github.com/mpv-player/mpv/pull/10669
Does it mean that there is a native VAAPI for Vulkan?
