### ISSUE TITLE
Want to work on mpv? macOS TODOs

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#13608]
you want to work on macOS parts in mpv and don't know where to start? there are open [macOS](https://github.com/mpv-player/mpv/labels/os%3Amac) issues that could possibly fixed. though this might not be a good or easy start into mpv.

there are various things i still want to do, with varying difficulties and different scopes. some of these are a good start into our code and can be done independently from any other tasks. anyway, my plan is to finish every task on the list and let you know of my current status. if you want to do any of those yourself, just let me know and i will gladly leave that to you and assist you if needed. this issue is to keep track of people working on those various things and coordinating that work properly.

### TODOs
- [ ] :green_circle: update [wiki](https://github.com/mpv-player/mpv/wiki/Compiling-distro-releases-for-macOS) for compiling distro releases
- [ ] :green_circle: remove unused functions form [libmpv_helper](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/libmpv_helper.swift#L198-L218)
- [ ] :green_circle: move c<>swift type bridging into type_helper.swift
	- [ ] [libmpv_helper](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/libmpv_helper.swift#L238-L253)
	- [ ] [mpv_helper](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/mpv_helper.swift#L149-L181)
- [ ] :green_circle: :one: move all none application related functionality out of [mac/application](https://github.com/mpv-player/mpv/blob/master/osdep/mac/application.m)
- [ ] :yellow_circle: move `macOptsPtr`, `macOpts`, `optsCachePtr`, `optsPtr`, etc from [libmpv_helper](https://github.com/mpv-player/mpv/blob/master/osdep/mac/libmpv_helper.swift) and [mpv_helper](https://github.com/mpv-player/mpv/blob/master/osdep/mac/mpv_helper.swift) into new options_helper.swift
- [ ] :yellow_circle: move input_ctx related functionality from [mpv_helper](https://github.com/mpv-player/mpv/blob/master/osdep/mac/mpv_helper.swift) into new input_helper.swift, similar to [log_helper](https://github.com/mpv-player/mpv/blob/master/osdep/mac/log_helper.swift)
- [ ] :yellow_circle: :two: move input_ctx related functionality from [mac/events](https://github.com/mpv-player/mpv/blob/master/osdep/mac/events.m) into new input_helper.swift, similar to [log_helper](https://github.com/mpv-player/mpv/blob/master/osdep/mac/log_helper.swift)
- [ ] :yellow_circle: rewrite [mac/menubar](https://github.com/mpv-player/mpv/blob/master/osdep/mac/menubar.m) in swift, similar to [remote_command_center](https://github.com/mpv-player/mpv/blob/master/osdep/mac/remote_command_center.swift)
- [ ] :yellow_circle: :four: rewrite [mac/touchbar.m](https://github.com/mpv-player/mpv/blob/master/osdep/mac/touchbar.m) in swift, similar to [remote_command_center](https://github.com/mpv-player/mpv/blob/master/osdep/mac/remote_command_center.swift)
- [ ] :yellow_circle: rewrite bundling scripts [dylib_unhell.py](https://github.com/mpv-player/mpv/blob/master/TOOLS/dylib_unhell.py) and [osxbundle.py](https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle.py) in swift
- [ ] :red_circle: :three: write an EventSubscriber service to get rid of the duplication of `processEvent` and `handlePropertyChange`:
	- [ ] [remote_command_center](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/remote_command_center.swift#L175-L213)
	- [ ] [mac/touchbar](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/touchbar.m#L298-L334) (depends on :four:)
	- [ ] [mac/event](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/events.m#L278-L315)
	- [ ] [cocoa_cb_common](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/video/out/cocoa_cb_common.swift#L224-L231)
	- [ ] [mac/application](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/osdep/mac/application.m#L176-L184)
- [ ] :red_circle: rewrite [mac/events](https://github.com/mpv-player/mpv/blob/master/osdep/mac/events.m) in swift (depends on :two: :three:)
- [ ] :red_circle: rewrite [mac/application](https://github.com/mpv-player/mpv/blob/master/osdep/mac/application.m) in swift (depends on :one: :three:)
- [ ] :red_circle: rewrite messy [`calculateWindowPosition` function](https://github.com/mpv-player/mpv/blob/8ba6d8f7a9aa3b049b4706e3f26bb614e95f965a/video/out/mac/window.swift#L392-L459) with a nonlinear function
- [ ] :red_circle: find maintainer for CoreAudio code

### Legend
| Difficulty                         | Dependencies                      |
| ----------------------- | --------------------------  |
| :red_circle: hard             | :one: :two: :three: :four: ...  |
| :yellow_circle: medium  |                                               |
| :green_circle: easy        |                                               |

**Comment by N-R-K** [comment]
> add a way to package mpv scripts/shaders/etc. and make them updatable, to automatically manage these scripts

I have a very rough proof-of-concept for managing plugins via `git`. Currently tested on linux and windows 10: https://codeberg.org/NRK/mpvget

My [current opinion](https://codeberg.org/NRK/mpvget#no-standardized-directory-structure) from working on this is that the ideal long term solution would be for `mpv` project to come up with a standardized plugin directory structure (similar to `vim`) and somehow get everyone to update their plugin to conform to such structure. It would eliminate the need for external "package managers" since you can basically just use git submodules at that point.

- - -

Also why hand-write markdown tables in here instead of just using github labels? It seems much more flexible. E.g you can have `meta:difficulty-{easy,mid,hard}` tags for difficulty. We already have `os:*` tags. And github issues also supports "assignees" already.

**Comment by Akemi** [comment]
> Also why hand-write markdown tables in here instead of just using github labels? It seems much more flexible. E.g you can have `meta:difficulty-{easy,mid,hard}` tags for difficulty. We already have `os:*` tags. And github issues also supports "assignees" already.

i am not really writing the table by hand though. various reasons:
- i don't think the issue tracker is a place for code cleanup and refactoring work. it should be kept to issues, feature request, etc
- the issue tracker is imo already full enough
- the point of this list, is the list itself and not being 'hidden' in the issues
- if there isn't any interested from anyone working on any of the then created 'issues', it would have been a waste of effort and time creating those (filling them with info etc)
- issues on the tracker can still be created when work has been picked by someone and it feels appropriate for communication and/or discussion
- atm it's mostly just my personal backlog/worklog
- i wanted to see if there is even a general interest in this, by people who want to work on something and by others filling the various lists
- imo the issue tracker isn't really more flexible. it just has a different presentation with a set amount of features that can be used to track such things. though if you need something more specific that can't be mapped to any of the features, your are out of luck. in that case some custom list can be extended with such things. eg previously there was a field with dependencies, that indicated which issues depend on other issues.

**Comment by addycb** [comment]
Any more info on the calculateWindowPosition requirements? Or on the advantage of a nonlinear function here

**Comment by Akemi** [comment]
the hope is to considerably simplify the whole function. atm it's a lot of ifs and it's hard to know/see what those are for.

the function also handles the case that the window changes screens or the screen resolution changes (when in fs), and the window is placed relative at the same position but the same size as before. with a linear function this would place the window off-screen in some cases.

also it seems the function broke a bit over the iterations of new macOS versions and does place the window at weird positions in some cases.

**Comment by ahaoboy** [comment]
I implemented a script manager some time ago, maybe it's not the best solution, but it can provide some ideas.

https://github.com/mpv-easy/mpsm-scripts

**Comment by Akemi** [comment]
just a heads-up, i added a bunch of new macOS TODOs.

**Comment by ilkermeliksitki** [comment]
Hello @Akemi, I can work with the task `add CI workflows to mpv-build`. Could you kindly guide me? I would appreciate your guidance.

**Comment by Akemi** [comment]
@ilkermeliksitki i believe @sfan5 added this to the list, pinging him since i am not sure what this encompasses.

**Comment by NekoAsakura** [comment]
Hi @Akemi, do you know if anyone is currently working on `calculateWindowPosition`? If not, I plan to do it later.

**Comment by Akemi** [comment]
as far as i know, no. feel free to.

**Comment by sfan5** [comment]
> @ilkermeliksitki i believe @sfan5 added this to the list, pinging him since i am not sure what this encompasses.

[mpv-build](https://github.com/mpv-player/mpv-build) is collection of scripts to compile mpv and select dependencies, intended for situations where recent software is not available from the repositories. There's also a package template for debian-based distros.
Currently there is no automated testing to see if they still work.
So we should have two CI workflows that run on something recent (e.g. Ubuntu 24.04):
1. one that just runs the scripts: we should get a functioning mpv binary
2. one that invokes the debian packaging stuff: we should get a deb package

**Comment by kasper93** [comment]
> [mpv-build](https://github.com/mpv-player/mpv-build) is collection of scripts to compile mpv and select dependencies, intended for situations where recent software is not available from the repositories.

1 and 3 could be single workflow definition run on multiple targets (as matrix) for this reason. Those scripts should work generally "anywhere". So we could have a matrix to invoke them on a range of target platforms, that we consider as "currently supported". We can start with single target obviously, too minimize complexity and expand if needed.

**Comment by ilkermeliksitki** [comment]
Thank you @sfan5 and @kasper93 for the helpful suggestions. I started tackling the first point of task and for now I got the following `mpv` binary in a `Ubuntu 24.04` Docker image. I guess `d3d11` is related to Windows operating system but what about libmpv? I installed `libmpv-dev` dependency and I get still `NO`. Is it expected?

```
mpv 0.39.0-UNKNOWN

    d3d11     : NO
    javascript: YES
    libmpv    : NO
    lua       : YES
    opengl    : YES
    vulkan    : YES
    wayland   : YES
    x11       : YES
```

**Comment by sfan5** [comment]
mpv-build does not build libmpv by default, working as intended.

**Comment by markfilipak-windows** [comment]
I want to entice folks to participate by posting the tables below. Note that no HD that I've seen is actually 24000/1001 fps. Note that only 2 of 22 SDs that I've seen are actually 24000/1001 fps, and they are jerky. Surprisingly, smooth 24000/1001 fps (i.e. the first line of the lower table) has not been seen -- there are smooth DVDs, but they're not 24000/1001 fps. What's important here is that MPV is not accurate. Regarding FFmpeg and what it does to audio sync, well, that's a sad story.
```
========================================= FOR BLURAY HD SOURCES ============================
  MPV REPORTS [1]      COMB IDENTITY  EXACT TPF [2]       EXACT FPS [3]                 SEEN
specified estimated
     23.97602      [6] none 23.98082  3753                90000/3753 = 10000/417         41

===================================== FOR DVD OR BLURAY SD SOURCES =========================
  MPV REPORTS [1]      COMB IDENTITY  EXACT TPF [2]       EXACT FPS [3]                 SEEN
specified estimated
     23.97602          none fakeNTSC  3753+3754+3754+3754 90000/(15015/4) = 24000/1001    0
-varies-  23.97602     none fakeNTSC  3003+3003+3003+3003 90000/(45045/12) = 24000/1001   1
                                     +3003+6006+3003+3003
                                     +6006+3003+3003+6006
-varies-  23.97602     none fakeNTSC  3003+3003+4505+4504 90000/(45045/12) = 24000/1001   1
                                     +4505+3003+3003+3003
                                     +4504+4504+4504+3004
-varies-  23.97602 [4] none 23.97762  4504+3003           90000/(7507/2) = 180000/7507   15
-varies-  29.980   [5] 2of5 29.98001  3002                90000/3002 = 45000/1501         1
     23.97602      [6] none 23.98082  3753                90000/3753 = 10000/417          0
-varies-  23.981   [6] none 23.98082  3753                90000/3753 = 10000/417          1
     24.00000          none cinema    3750                90000/3750 = 24                 0
     25.00000          none fakePAL   3600                90000/3600 = 25                 1
     25.00000          all  PAL-TV    3600                90000/3600 = 25                 0
     29.97003          2of5 hardNTSC  3003                90000/3003 = 30000/1001         1
     29.97003          all  NTSC-TV   3003                90000/3003 = 30000/1001         1
```
NOTES:
[1] If MPV doesn't show separate "(specified)" and "(estimated)", then the Frame Rate applies to both.
    When watching via MPV, don't accept the first FPS but wait a minute or two to see if "fps (estimated)" changes.
    It often happens that studio splash screens have different FPSes (e.g. that 29.97003 'settles' to 23.97602, for example).
    Accept the 'settled' "fps (estimated)" value.
[2] Integer ticks per frame as reported by 'showinfo'. To report, for example, the first 1000 TPFs:
    ffmpeg -hide_banner -i "%1" -frames:v 999 -vf showinfo=checksum=0 -c:v rawvideo -f null -muxdelay 0 -
    Note that for MPEG2 SDs found on DVDs, there usually are 12 frames per GOP.
[3] Frames per second (as rational numbers).
[4] Should be 23.97762 (i.e. MPV's report is in error).
[5] Should be 29.98001 (i.e. MPV's report is in error); played by old MPV.
[6] Should be 23.98082 (i.e. MPV's report is in error).
[7] Should be 24.09639 (i.e. MPV's report is in error).

**Comment by Traneptora** [comment]
Deleted comments that were spam. They contained PII so I deleted them rather than hide them.
